// Code generated by MockGen. DO NOT EDIT.
// Source: C:\GoWork\src\github.com\QuarkChain\goquarkchain\cluster\master\interface.go

// Package mock_master is a generated GoMock package.
package mock_master

import (
	rpc "github.com/QuarkChain/goquarkchain/cluster/rpc"
	p2p "github.com/QuarkChain/goquarkchain/p2p"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockShardConnForP2P is a mock of ShardConnForP2P interface
type MockShardConnForP2P struct {
	ctrl     *gomock.Controller
	recorder *MockShardConnForP2PMockRecorder
}

// MockShardConnForP2PMockRecorder is the mock recorder for MockShardConnForP2P
type MockShardConnForP2PMockRecorder struct {
	mock *MockShardConnForP2P
}

// NewMockShardConnForP2P creates a new mock instance
func NewMockShardConnForP2P(ctrl *gomock.Controller) *MockShardConnForP2P {
	mock := &MockShardConnForP2P{ctrl: ctrl}
	mock.recorder = &MockShardConnForP2PMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockShardConnForP2P) EXPECT() *MockShardConnForP2PMockRecorder {
	return m.recorder
}

// AddTransactions mocks base method
func (m *MockShardConnForP2P) AddTransactions(request *p2p.NewTransactionList) (*rpc.HashList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransactions", request)
	ret0, _ := ret[0].(*rpc.HashList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTransactions indicates an expected call of AddTransactions
func (mr *MockShardConnForP2PMockRecorder) AddTransactions(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransactions", reflect.TypeOf((*MockShardConnForP2P)(nil).AddTransactions), request)
}

// GetMinorBlocks mocks base method
func (m *MockShardConnForP2P) GetMinorBlocks(request *p2p.GetMinorBlockListRequest) (*p2p.GetMinorBlockListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinorBlocks", request)
	ret0, _ := ret[0].(*p2p.GetMinorBlockListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinorBlocks indicates an expected call of GetMinorBlocks
func (mr *MockShardConnForP2PMockRecorder) GetMinorBlocks(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinorBlocks", reflect.TypeOf((*MockShardConnForP2P)(nil).GetMinorBlocks), request)
}

// GetMinorBlockHeaders mocks base method
func (m *MockShardConnForP2P) GetMinorBlockHeaders(request *p2p.GetMinorBlockHeaderListRequest) (*p2p.GetMinorBlockHeaderListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinorBlockHeaders", request)
	ret0, _ := ret[0].(*p2p.GetMinorBlockHeaderListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinorBlockHeaders indicates an expected call of GetMinorBlockHeaders
func (mr *MockShardConnForP2PMockRecorder) GetMinorBlockHeaders(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinorBlockHeaders", reflect.TypeOf((*MockShardConnForP2P)(nil).GetMinorBlockHeaders), request)
}

// HandleNewTip mocks base method
func (m *MockShardConnForP2P) HandleNewTip(request *p2p.Tip) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleNewTip", request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleNewTip indicates an expected call of HandleNewTip
func (mr *MockShardConnForP2PMockRecorder) HandleNewTip(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNewTip", reflect.TypeOf((*MockShardConnForP2P)(nil).HandleNewTip), request)
}

// AddMinorBlock mocks base method
func (m *MockShardConnForP2P) AddMinorBlock(request *p2p.NewBlockMinor) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMinorBlock", request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMinorBlock indicates an expected call of AddMinorBlock
func (mr *MockShardConnForP2PMockRecorder) AddMinorBlock(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMinorBlock", reflect.TypeOf((*MockShardConnForP2P)(nil).AddMinorBlock), request)
}
